# -*- coding: utf-8 -*-
"""next_churn_v3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AKhDNg6RqP5cQpYdOOXdEdO4SBCKoPVH
"""

import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import lightgbm as lgb

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# ----------------------------------
# 1. 데이터 로드 및 정렬
# ----------------------------------

df = pd.read_csv('extracted_data.csv')
df = df.sort_values(by=['id', 'year']).reset_index(drop=True)

print(f'전체 행: {len(df):,}  |  고유 고객: {df["id"].nunique():,}')

# ----------------------------------
# 2. 파생변수 생성
# ----------------------------------

# 통신사 변경 이력
df['prev_provider']    = df.groupby('id')['provider'].shift(1)
df['provider_changed'] = (df['provider'] != df['prev_provider']).astype(int)
df['total_changes']    = df.groupby('id')['provider_changed'].cumsum()

# 전년 대비 통신비 변화율
df['prev_cost']         = df.groupby('id')['monthly_total_cost'].shift(1)
df['cost_change_rate']  = (df['monthly_total_cost'] - df['prev_cost']) / (df['prev_cost'] + 1)

# 가입 기간
df['tenure'] = df.groupby('id').cumcount() + 1

print('파생변수 생성 완료')
print(f'  - provider_changed : 전년 대비 통신사 변경 여부')
print(f'  - total_changes    : 누적 통신사 변경 횟수')
print(f'  - cost_change_rate : 전년 대비 통신비 변화율')
print(f'  - tenure           : 가입 기간 (관측 연수)')

# ----------------------------------
# 3. next_provider 생성
# ----------------------------------

df['next_provider'] = df.groupby('id')['provider'].shift(-1)

provider_map = {1.0: 'SKT', 2.0: 'KT', 3.0: 'LGU+'}

print('[next_provider 분포]')
print(df['next_provider'].value_counts(dropna=False))

# ----------------------------------
# 4. 실제 전환 이탈 고객 추출
# ----------------------------------

switching_df = df[
    (df['churn'] == 1.0) &
    (df['next_provider'].notna()) &
    (df['provider'].notna()) &
    (df['provider'].isin([1.0, 2.0, 3.0])) &
    (df['next_provider'].isin([1.0, 2.0, 3.0])) &
    (df['provider'] != df['next_provider'])
].copy()

print(f'대상 고객 수: {len(switching_df):,}명')
print('\n[현재 통신사 분포]')
print(switching_df['provider'].map(provider_map).value_counts())
print('\n[이동 통신사 분포]')
print(switching_df['next_provider'].map(provider_map).value_counts())

# ----------------------------------
# 5. 전처리
# ----------------------------------

switching_df['monthly_installment'] = switching_df['monthly_installment'].fillna(0)
switching_df['monthly_total_cost']  = switching_df['monthly_total_cost'].fillna(switching_df['monthly_total_cost'].median())
switching_df['is_mobile_bundled']   = switching_df['is_mobile_bundled'].fillna(0)
switching_df['household_size']      = switching_df['household_size'].fillna(switching_df['household_size'].median())
switching_df['prev_cost']           = switching_df['prev_cost'].fillna(switching_df['monthly_total_cost'])
switching_df['cost_change_rate']    = switching_df['cost_change_rate'].fillna(0)
switching_df['provider_changed']    = switching_df['provider_changed'].fillna(0)
switching_df['total_changes']       = switching_df['total_changes'].fillna(0)

# 피처 목록
features = [
    # 기존 피처
    'age', 'gender', 'income', 'school', 'area', 'job', 'marriage',
    'monthly_total_cost', 'monthly_installment', 'cost_payer',
    'provider', 'household_size', 'is_mobile_bundled',
    # 신규 파생변수
    'provider_changed', 'total_changes', 'cost_change_rate', 'tenure'
]

X = switching_df[features]
y = switching_df['next_provider'].astype(int)

le = LabelEncoder()
y_encoded    = le.fit_transform(y)
target_names = [provider_map[float(cls)] for cls in le.classes_]

print(f'피처 수: {len(features)}개')
print(f'클래스: {target_names}')

# ----------------------------------
# 6. 학습 / 검증 분할 (8:2)
# ----------------------------------

X_train, X_val, y_train, y_val = train_test_split(
    X, y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

print(f'Train: {len(X_train):,}  |  Val: {len(X_val):,}')
print('\n[Train 클래스 분포]')
print(pd.Series(y_train).value_counts().rename(index=dict(enumerate(target_names))))

# ----------------------------------
# 7. 모델 학습
# ----------------------------------

params = {
    'objective'        : 'multiclass',
    'num_class'        : len(le.classes_),
    'metric'           : 'multi_logloss',
    'boosting_type'    : 'gbdt',
    'learning_rate'    : 0.05,
    'num_leaves'       : 15,
    'min_child_samples': 20,
    'subsample'        : 0.8,
    'colsample_bytree' : 0.8,
    'reg_alpha'        : 0.5,
    'reg_lambda'       : 0.5,
    'class_weight'     : 'balanced',
    'random_state'     : 42,
    'verbose'          : -1
}

train_data = lgb.Dataset(X_train, label=y_train)
val_data   = lgb.Dataset(X_val,   label=y_val, reference=train_data)

model = lgb.train(
    params,
    train_data,
    num_boost_round=1000,
    valid_sets=[train_data, val_data],
    callbacks=[
        lgb.early_stopping(stopping_rounds=30, verbose=False),
        lgb.log_evaluation(-1)
    ]
)

print('train finish')

# ----------------------------------
# 8. 평가
# ----------------------------------

y_val_prob = model.predict(X_val)
y_val_pred = np.argmax(y_val_prob, axis=1)

print('========================================================')
print(f' [모델 평가] 검증 데이터셋 정확도: {accuracy_score(y_val, y_val_pred):.2%}')
print('========================================================')

print('\n[Classification Report]')
print(classification_report(y_val, y_val_pred, target_names=target_names))

print('[Confusion Matrix]')
cm = confusion_matrix(y_val, y_val_pred)
cm_df = pd.DataFrame(
    cm,
    index=[f'실제_{t}'   for t in target_names],
    columns=[f'예측_{t}' for t in target_names]
)
print(cm_df)

# ----------------------------------
# 9. 변수 중요도
# ----------------------------------

importance_df = pd.DataFrame({
    'feature'   : features,
    'importance': model.feature_importance(importance_type='gain')
}).sort_values('importance', ascending=False).reset_index(drop=True)

print('[변수 중요도 Top 17]')
print(importance_df.to_string(index=False))

# ----------------------------------
# 10. 최종 결과 출력
# ----------------------------------

pred_probs       = model.predict(X)
pred_indices     = np.argmax(pred_probs, axis=1)
max_probs        = np.max(pred_probs, axis=1)
predicted_labels = le.inverse_transform(pred_indices)

switching_df['현재 통신사']      = switching_df['provider'].map(provider_map)
switching_df['실제 다음 통신사'] = switching_df['next_provider'].map(provider_map)


# 통신사별 확률 컬럼 추가
for i, name in enumerate(target_names):
    switching_df[f'{name} 이동 확률(%)'] = [f'{p[i]*100:.1f}%' for p in pred_probs]

output_cols = (
    ['id', 'year', '현재 통신사'] +
    [f'{t} 확률(%)' for t in target_names] +
    [ '실제 다음 통신사']
)

result_show = switching_df[output_cols].head(10).copy()
result_show.columns = (
    ['고객 ID', '이탈 연도', '현재 통신사'] +
    [f'{t} 확률(%)' for t in target_names] +
    [ '실제 다음 통신사']
)

print('========== 이탈 고객별 차기 통신사 예측 결과 (상위 10개) ==========')
print(result_show.to_string(index=False))